nft_collection:
  data: fift/collection-data.fif
  func:
    - func/utils/helpers.func
    - func/utils/params.func
    - func/utils/op-codes.func
    - func/nft-collection.func
  tests:
    - tests/collection-tests.func
    - tests/collection-tests-int.func

nft_marketplace:
  data: fift/marketplace-data.fif
  func:
    - func/utils/helpers.func
    - func/utils/params.func
    - func/utils/op-codes.func
    - func/nft-marketplace.func
  tests:
    - tests/marketplace-tests.func

nft_sale:
  data: fift/sale-data.fif
  func:
    - func/utils/helpers.func
    - func/utils/params.func
    - func/utils/op-codes.func
    - func/nft-sale.func
  tests:
    - tests/sale-tests.func

nft:
  data: fift/nft-data.fif
  func:
    - func/utils/helpers.func
    - func/utils/params.func
    - func/utils/op-codes.func
    - func/nft-item.func
  tests:
    - tests/nft-tests.func
    - tests/nft-tests-int.func
